baseurl = "https://h-sao.com/"
languageCode = "ja-jp"
title = "Effectiveさお"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "harukasao"
theme = "minimalist"

# pygmentsUseClasses = true
pygmentsCodefences = true
PygmentsOptions = "linenos=table"

[author]
    name = "遥佐保/Sao Haruka"

[params]
    site_author = "遥佐保/Sao Haruka"
    site_description = "The awesome blog of Sao Haruka."
    location = "Japan"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "pic/saoharuka128.png"
    header_background = "pic/SiteTop.jpg"
    header_title = "Effectiveさお"
    copyright = "Copyright © Sao Haruka<br> Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-66721712-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "hr_sao"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "h-sao"
    gplus     = ""

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    # post = "/blog/:year/:month/:day/:title/"
    post = "/blog/:year/:month/:day/:filename/"
